INSERT INTO public.study_items (title, author, year, type, sort_order, completed) VALUES
  ('Attention Is All You Need', 'Vaswani et al.', '2017', 'paper', 1, FALSE),
  ('The Illustrated Transformer', 'Jay Alammar', '2018', 'paper', 2, FALSE),
  ('BERT: Pre-training of Deep Bidirectional Transformers', 'Devlin et al.', '2018', 'paper', 3, FALSE),
  ('Language Models are Few-Shot Learners (GPT-3)', 'Brown et al.', '2020', 'paper', 4, FALSE),
  ('Scaling Laws for Neural Language Models', 'Kaplan et al.', '2020', 'paper', 5, FALSE),
  ('Training Compute-Optimal Large Language Models (Chinchilla)', 'Hoffmann et al.', '2022', 'paper', 6, FALSE),
  ('LLaMA: Open and Efficient Foundation Language Models', 'Touvron et al.', '2023', 'paper', 7, FALSE),
  ('RoFormer: Rotary Position Embedding', 'Su et al.', '2021', 'paper', 8, FALSE),
  ('FlashAttention', 'Dao et al.', '2022', 'paper', 9, FALSE),
  ('Retrieval-Augmented Generation (RAG)', 'Lewis et al.', '2020', 'paper', 10, FALSE),
  ('Training Language Models to Follow Instructions with Human Feedback (InstructGPT)', 'Ouyang et al.', '2022', 'paper', 11, FALSE),
  ('Direct Preference Optimization (DPO)', 'Rafailov et al.', '2023', 'paper', 12, FALSE),
  ('Chain-of-Thought Prompting Elicits Reasoning in Large Language Models', 'Wei et al.', '2022', 'paper', 13, FALSE),
  ('ReAct: Reasoning and Acting', 'Yao et al.', '2022', 'paper', 14, FALSE),
  ('DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning', 'Guo et al.', '2025', 'paper', 15, FALSE),
  ('Qwen3 Technical Report', 'Yang et al.', '2025', 'paper', 16, FALSE),
  ('Outrageously Large Neural Networks: Sparsely-Gated Mixture of Experts', 'Shazeer et al.', '2017', 'paper', 17, FALSE),
  ('Switch Transformers', 'Fedus et al.', '2021', 'paper', 18, FALSE),
  ('Mixtral of Experts', 'Mistral AI', '2024', 'paper', 19, FALSE),
  ('Sparse Upcycling: Training Mixture-of-Experts from Dense Checkpoints', 'Komatsuzaki et al.', '2022', 'paper', 20, FALSE),
  ('The Platonic Representation Hypothesis', 'Huh et al.', '2024', 'paper', 21, FALSE),
  ('Textbooks Are All You Need', 'Gunasekar et al.', '2023', 'paper', 22, FALSE),
  ('Scaling Monosemanticity: Extracting Interpretable Features from Claude 3 Sonnet', 'Templeton et al.', '2024', 'paper', 23, FALSE),
  ('PaLM: Scaling Language Modeling with Pathways', 'Chowdhery et al.', '2022', 'paper', 24, FALSE),
  ('GLaM: Generalist Language Model', 'Du et al.', '2022', 'paper', 25, FALSE),
  ('The Smol Training Playbook', 'Hugging Face', '2025', 'paper', 26, FALSE),
  -- Example Courses
  ('Advanced Prompt Engineering', 'DeepLearning.AI', '2024', 'course', 1, FALSE),
  ('Agents and Function Calling', 'DeepLearning.AI', '2024', 'course', 2, FALSE);
